// data.js - ข้อมูลสมาชิกครอบครัวแบบ flat array
const familyRawData = [
  { id: "1", name: "นก", father: "", mother: "", spouse: ["2"], gender: "ช", photo: "" },
  { id: "2", name: "สวัสดิ์", father: "", mother: "", spouse: ["1"], gender: "ญ", photo: "" },
  { id: "3", name: "คำเป้า", father: "1", mother: "2", spouse: ["4"], gender: "ญ", photo: "" },
  { id: "4", name: "เดช", father: "", mother: "", spouse: ["3"], gender: "ช", photo: "" },
  { id: "5", name: "เขียว", father: "1", mother: "2", spouse: ["6"], gender: "ช", photo: "" },
  { id: "6", name: "นวล", father: "", mother: "", spouse: ["5"], gender: "ญ", photo: "" },
  { id: "7", name: "เหมย", father: "1", mother: "2", spouse: ["8"], gender: "ญ", photo: "" },
  { id: "8", name: "โอ๊ต", father: "", mother: "", spouse: ["7"], gender: "ช", photo: "" },
  { id: "9", name: "เจน", father: "1", mother: "2", spouse: ["10"], gender: "ช", photo: "" },
  { id: "10", name: "บุญเรือน", father: "", mother: "", spouse: ["9"], gender: "ญ", photo: "" },
  { id: "11", name: "แฮ่", father: "1", mother: "2", spouse: [], gender: "ช", photo: "" },
  { id: "12", name: "แก้ว", father: "4", mother: "3", spouse: ["20", "25", "26"], gender: "ช", photo: "" },
  { id: "13", name: "ขวัญ", father: "4", mother: "3", spouse: ["21"], gender: "ญ", photo: "" },
  { id: "14", name: "ตี๋", father: "5", mother: "6", spouse: ["32", "33", "34"], gender: "ช", photo: "" },
  { id: "15", name: "คู่", father: "5", mother: "6", spouse: ["22"], gender: "ช", photo: "" },
  { id: "16", name: "ปุ้ย", father: "7", mother: "8", spouse: ["23"], gender: "ญ", photo: "" },
  { id: "17", name: "ป๊อบ", father: "7", mother: "8", spouse: ["24"], gender: "ญ", photo: "" },
  { id: "18", name: "ทิต", father: "10", mother: "9", spouse: [], gender: "ช", photo: "" },
  { id: "19", name: "แวน", father: "10", mother: "9", spouse: [], gender: "ช", photo: "" },
  { id: "20", name: "น็อต", father: "", mother: "", spouse: ["12"], gender: "ญ", photo: "" },
  { id: "21", name: "ตอง", father: "", mother: "", spouse: ["13"], gender: "ช", photo: "" },
  { id: "22", name: "นุ้ย", father: "", mother: "", spouse: ["15"], gender: "ญ", photo: "" },
  { id: "23", name: "แชม", father: "", mother: "", spouse: ["16"], gender: "ช", photo: "" },
  { id: "24", name: "สมชาย", father: "", mother: "", spouse: ["17"], gender: "ช", photo: "" },
  { id: "25", name: "ดาว", father: "", mother: "", spouse: ["12"], gender: "ญ", photo: "" },
  { id: "26", name: "เบนซ์", father: "", mother: "", spouse: ["12"], gender: "ช", photo: "" },
  { id: "27", name: "เอ", father: "12", mother: "20", spouse: [], gender: "ญ", photo: "" },
  { id: "28", name: "อิ่ง", father: "12", mother: "20", spouse: [], gender: "ญ", photo: "" },
  { id: "29", name: "โดนัท", father: "21", mother: "13", spouse: [], gender: "ช", photo: "" },
  { id: "30", name: "โมนา", father: "21", mother: "13", spouse: [], gender: "ญ", photo: "" },
  { id: "31", name: "อะตอม", father: "15", mother: "22", spouse: [], gender: "ช", photo: "" },
  { id: "32", name: "โต้ง", father: "", mother: "", spouse: ["14"], gender: "ญ", photo: "" },
  { id: "33", name: "ต๋อง", father: "", mother: "", spouse: ["14"], gender: "ญ", photo: "" },
  { id: "34", name: "...", father: "", mother: "", spouse: ["14"], gender: "ญ", photo: "" }
];
